name: dart_hydrologis_db
description: Dart based db utilities.
version: 0.5.0+1
repository: https://github.com/moovida/dart_hydrologis_db
issue_tracker: https://github.com/moovida/dart_hydrologis_db/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
 path: ^1.7.0

 # MIT
 sqlite3: ^0.1.4

 # BSD 
 postgres: ^2.2.0

 # BSD
 stack_trace: ^1.9.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
