name: dart_hydrologis_db
description: Dart based db utilities.
version: 1.0.0+1
repository: https://github.com/moovida/dart_hydrologis_db
issue_tracker: https://github.com/moovida/dart_hydrologis_db/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 path: ^1.8.2

 # MIT
 sqlite3: ^1.8.0

 # BSD 
 postgres: ^2.5.1

 # BSD
 stack_trace: ^1.10.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
