name: dart_hydrologis_db
description: Dart moor based db utilities.
version: 0.2.0
homepage: https://www.hydrologis.com
repository: https://github.com/moovida/dart_hydrologis_db
issue_tracker: https://github.com/moovida/dart_hydrologis_db/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
 path: ^1.7.0

 dart_jts: ^0.0.5+4
  #    git:
  #      url: https://github.com/moovida/dart_jts.git

 # MIT
 moor_ffi: #^0.6.0
  git:
    url: https://github.com/moovida/moor.git
    ref: develop
    path: moor_ffi

 # BSD
 stack_trace: ^1.9.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
