name: dart_hydrologis_db
description: Dart based db utilities.
version: 1.1.0
repository: https://github.com/moovida/dart_hydrologis_db
issue_tracker: https://github.com/moovida/dart_hydrologis_db/issues

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:

  dart_hydrologis_utils: ^0.8.1

  path: ^1.8.2

  # MIT
  sqlite3: ^2.1.0

  # BSD 
  postgres: ^2.6.2

  # BSD
  stack_trace: ^1.11.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
